Disable L3
consensus-shipyard/ipc pull request #678
Opened 2024-02-08 08:34 UTC by cryptoAtwill

Reenable disable L3 subnet.

2024-02-08 09:12 UTC, dnkolegov requested changes

2024-02-08 09:22 UTC, cryptoAtwill commented on contracts/src/gateway/GatewayManagerFacet.sol
> +        if (s.networkName.route.length + 1 >= s.maxTreeDepth) {
so the concern is probably the check is wrong?

2024-02-08 09:28 UTC, dnkolegov commented on contracts/src/gateway/GatewayManagerFacet.sol
> +        if (s.networkName.route.length + 1 >= s.maxTreeDepth) {
Yes, they suggest using `>` instead of `>=`

2024-02-08 14:12 UTC, maciejwitowski commented on contracts/src/gateway/GatewayManagerFacet.sol
> +        if (s.networkName.route.length + 1 >= s.maxTreeDepth) {
Yeah, I think `>` should be used. Wanted to check on a few cases below. 
@cryptoAtwill could you add a unit test(s) for this as part of this PR?

- Case 1: 
  - We allow L2 so `s.maxTreeDepth` == 2
  - Someone tries to register L2:  the route is `r123/abcd` so `s.networkName.route.length` is 1 (`abcd`)
  - This check is then 1 + 1 > 2
  - The condition isn't met so it DOESN'T revert

- Case 2: 
  - We allow L2 so `s.maxTreeDepth` == 2
  - Someone tries to register L3:  the route is `r123/abcd/efgh` so `s.networkName.route.length` is 2 (`abcd/efgh`)
  - This check is then 3 + 1 > 2
  - The condition is met so it DOES revert

- Case 3: Let's say L3 is allowed -> `s.maxTreeDepth` == 3
  - The route for L3 is `r123/abcd/efgh` so `s.networkName.route.length` is 2 (`abcd/efgh`)
  - This check is then 2 + 1 > 3
  - The condition isn't met so it DOESN't revert

2024-02-08 15:21 UTC, cryptoAtwill commented on contracts/src/gateway/GatewayManagerFacet.sol
> +        if (s.networkName.route.length + 1 >= s.maxTreeDepth) {
I think this check is correct. For L1, the route.length is 0, for L2 the route.length is 1. `s.maxTreeDepth` is default to 2. So to create L3, we will have L2's `route.length + 1` which is 2 and equals `s.maxTreeDepth`.

2024-02-08 15:23 UTC, cryptoAtwill commented on contracts/src/gateway/GatewayManagerFacet.sol
> +        if (s.networkName.route.length + 1 >= s.maxTreeDepth) {
@dnkolegov @maciejwitowski I think your examples mixed `subnetId` with `s.networkName`. `s.networkName` is the current subnet and `subnetId` is the subnet to be created. This check is sent to the parent.

2024-02-08 15:26 UTC, cryptoAtwill commented on contracts/src/gateway/GatewayManagerFacet.sol
> +        if (s.networkName.route.length + 1 >= s.maxTreeDepth) {
@dnkolegov @maciejwitowski I think your examples mixed `subnetId` with `s.networkName`. `s.networkName` is the current subnet and `subnetId` is the subnet to be created. This check is sent to the parent.

2024-02-08 15:35 UTC, maciejwitowski commented on contracts/src/gateway/GatewayManagerFacet.sol
> +        if (s.networkName.route.length + 1 >= s.maxTreeDepth) {
> I think your examples mixed subnetId with s.networkName. s.networkName is the current subnet and subnetId is the subnet to be created. This check is sent to the parent.

Oh, I missed the fact this `if` is before the `s.networkName.createSubnetId` so in flow of creating L3 the `s.networkName.route.length` is the one for L2 (which is 1). You may be right then 😄 
Anyways, adding a few unit tests with clear names like `revert_L3_creation_when_it_is_disabled` which test the edge conditions of `>=` would be recommended here I think.

2024-02-08 16:46 UTC, maciejwitowski approved these changes

2024-02-08 16:47 UTC, dnkolegov approved these changes

2024-02-09 09:02 UTC, merged

2024-02-09 10:00 UTC, aakoshh commented on contracts/src/gateway/GatewayManagerFacet.sol
> +        if (s.networkName.route.length + 1 >= s.maxTreeDepth) {
This got me too as well in the past. Comments would be good because it looks like there is nobody who has looked at this and can tell what it does.