Adding instrucment
consensus-shipyard/ipc pull request #762
Opened 2024-02-29 15:32 UTC by cryptoAtwill

Adding `#[instrument]` to debug topdown syncer performance issue.

2024-02-29 16:12 UTC, aakoshh approved these changes
LGTM :+1:

2024-02-29 16:14 UTC, aakoshh requested changes
Sorry, just noticed that the tests are actually failing: https://github.com/consensus-shipyard/ipc/actions/runs/8098552876/job/22132258717

2024-02-29 16:16 UTC, aakoshh approved these changes
Ah, no worries, I see this is going into the other branch where you are already fixing them.

2024-03-01 07:48 UTC, fridrik01 approved these changes
lgtm

2024-03-01 07:48 UTC, fridrik01 commented on fendermint/app/src/main.rs
> +                .with_span_events(FmtSpan::CLOSE)
The [documentation](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/struct.Layer.html#method.with_span_events) is a bit short in exact details, but I think if we use `FmtSpan::CLOSE` only like here then the generated event will also contain the total time the span was entered (+ time the span existed but was not entered).

2024-03-01 09:40 UTC, merged