forge requires :ContractName to execute
consensus-shipyard/ipc pull request #777
Opened 2024-03-08 07:53 UTC by snissn

This change lets the forge scripts execute for me

2024-03-13 16:24 UTC, fridrik01 commented
@snissn It would be good to know what errors this fixed for you :)

2024-03-16 10:31 UTC, jsoares approved these changes

2024-03-17 00:03 UTC, raulk requested changes
This isn't true for me (both with an old version of Foundry and having just updated). What error are you seeing?

2024-03-20 18:10 UTC, jsoares commented
@raulk by "not true", do you mean you didn't have the issue before or that it doesn't work with the changes? I didn't have any issues before or after, fwiw 🤷 

Anyhow, if only @snissn observed this behaviour, then it's probably something to debug rather than brute force.

2024-03-21 09:45 UTC, closed without merging